/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.common.domain;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EntityBaseTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        assertNotNull(new EntityBase(), "someLibraryMethod should return 'true'");
    }
}
