/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("com.codedifferently.studycrm.spring-library")
}

group = "com.codedifferently.studycrm.contact-service.persistence"

dependencies {
    implementation("com.codedifferently.studycrm.contact-service.domain:contact-domain-lib")

    implementation("io.eventuate.common:eventuate-common-jdbc")
}