/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.auth.api.messaging.commands;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CreateAuthUserCommandTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        assertNotNull(new CreateAuthUserCommand(), "someLibraryMethod should return 'true'");
    }
}
