/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("com.simplecrm.java-library")
}

group = "com.simplecrm.contact-service.web"

dependencies {
    implementation("com.simplecrm.contact-service.domain:contact-domain-lib")
    implementation("com.simplecrm.contact-service.persistence:contact-persistence-lib")

    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
}