/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.contacts;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest);
  }
}
