/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.common.web.exceptions;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class GlobalExceptionHandlerTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    assertNotNull(new GlobalExceptionHandler(), "someLibraryMethod should return 'true'");
  }
}
