/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.common.web.exceptions;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GlobalExceptionHandlerTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        assertNotNull(new GlobalExceptionHandler(), "someLibraryMethod should return 'true'");
    }
}
