/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.organizations.sagas;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AuthServiceProxyTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    assertNotNull(new AuthServiceProxy(), "someLibraryMethod should return 'true'");
  }
}
