/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.organizations.persistence;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class OrganizationPersistenceConfigurationTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    assertNotNull(
        new OrganizationPersistenceConfiguration(), "someLibraryMethod should return 'true'");
  }
}
