/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.organizations.persistence;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OrganizationPersistenceConfigurationTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        assertNotNull(new OrganizationPersistenceConfiguration(), "someLibraryMethod should return 'true'");
    }
}
