/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.simplecrm.contacts.web;

import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import static org.junit.jupiter.api.Assertions.assertEquals;

class ContactsControllerTest {
    @Test
    void testGetContactsResponse() {
        ContactsController contactsController = new ContactsController();
        ResponseEntity<String> response = contactsController.getContactsResponse();
        assertEquals(HttpStatus.OK, response.getStatusCode(), "Response status should be OK");
    }
}