/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.contacts.persistence;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ContactPersistenceConfigurationTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        assertNotNull(new ContactPersistenceConfiguration(), "someLibraryMethod should return 'true'");
    }
}
