/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("com.codedifferently.studycrm.java-library")
}

group = "com.codedifferently.studycrm.auth-service.web"

dependencies {
    implementation("com.codedifferently.studycrm.common.domain:common-domain-lib")
    implementation("com.codedifferently.studycrm.auth-service.domain:auth-domain-lib")
    implementation("com.codedifferently.studycrm.auth-service.persistence:auth-persistence-lib")
    implementation("com.codedifferently.studycrm.auth-service.api.web:auth-api-web-lib")

    implementation("io.eventuate.tram.core:eventuate-tram-spring-flyway")
    runtimeOnly("io.eventuate.tram.sagas:eventuate-tram-sagas-spring-flyway")

    implementation("io.eventuate.common:eventuate-common-jdbc")
    
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
	implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation("org.springframework.security:spring-security-oauth2-authorization-server")
    implementation("org.springframework.security:spring-security-cas")
    
    implementation("org.flywaydb:flyway-core")
    implementation("org.flywaydb:flyway-mysql")
}