/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.auth.messaging;

import static org.junit.jupiter.api.Assertions.*;

import com.codedifferently.studycrm.auth.domain.AuthService;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.mock.mockito.MockBean;

class AuthCommandHandlerTest {
  @MockBean private AuthService customerService;

  @Test
  void someLibraryMethodReturnsTrue() {
    assertNotNull(new AuthCommandHandler(), "someLibraryMethod should return 'true'");
  }
}
