/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.entities.layout.domain;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class LibraryTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    assertNotNull(new Container(), "someLibraryMethod should return 'true'");
  }
}
