/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.auth.web.config;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AuthSeverSecurityConfigTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        AuthSeverSecurityConfig classUnderTest = new AuthSeverSecurityConfig();
        assertTrue(classUnderTest.authorizationServerSecurityFilterChain(), "someLibraryMethod should return 'true'");
    }
}
