/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.auth.web.config;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AuthServerSecurityConfigTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    assertNotNull(new AuthServerSecurityConfig(), "someLibraryMethod should return 'true'");
  }
}
