/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.organizations.web;

import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import com.codedifferently.studycrm.organizations.web.OrganizationsController;

import static org.junit.jupiter.api.Assertions.assertEquals;

class OrganizationsControllerTest {
    @Test
    void testGetOrganizationsResponse() {
        assertEquals(HttpStatus.OK, HttpStatus.OK, "Response status should be OK");
    }
}