/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.contacts.web;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class ContactsControllerTest {
  @Test
  void testGetContactsResponse() {
    assertNotNull(new ContactsController(), "Response status should be OK");
  }
}
