/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.organizations.api.messaging.sagas.createOrganization;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class CreateOrganizationSagaDataTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    assertNotNull(new CreateOrganizationSagaData(), "someLibraryMethod should return 'true'");
  }
}
