/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedifferently.studycrm.organizations.api.messaging.sagas.createOrganization;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CreateOrganizationSagaDataTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        assertNotNull(new CreateOrganizationSagaData(), "someLibraryMethod should return 'true'");
    }
}
